data: !!python/object/apply:collections.OrderedDict
- - - fc1
    - bias:
        bitwidth: 4
        method: 2
        scale: -4
      weight:
        bitwidth: 4
        method: 2
        scale: -4
  - - fc2
    - bias:
        bitwidth: 4
        method: 2
        scale: -3
      weight:
        bitwidth: 4
        method: 2
        scale: -3
  - - fix0
    - activation:
        bitwidth: 4
        method: 2
        scale: 2
  - - fix1
    - activation:
        bitwidth: 4
        method: 2
        scale: 4
  - - fix2
    - activation:
        bitwidth: 4
        method: 2
        scale: 4
grad: !!python/object/apply:collections.OrderedDict
- - - fc1
    - {}
  - - fc2
    - {}
  - - fix0
    - {}
  - - fix1
    - {}
  - - fix2
    - {}
